### ISSUE TITLE
Bad Syntax 400

### ISSUE THREAD

**Issue by iGorrrrrrr** [PayU/plugin_woocommerce#10]
Hey,

I got problem with item price 19,90 (pln, 23% vat). On payment detail page, when click "Order & Pay" i got Błąd płatności: ERROR_SYNTAX - Bad syntax (400)

For 9,90 and from 29,90 to 99,90 there is no problem. Only for 19,90.

**Comment by lgrzesiak** [comment]
Hi, could you please contact with PayU technical support and provide more detailed info (including failed order details, like your POS ID in PayU, time and date etc.), so we can check the logs? Pls mail to: tech@payu.pl
