### ISSUE TITLE
Zamówienie zostanie usunięte kiedy płatność nie przejdzie

### ISSUE THREAD

**Issue by pkasperski** [PayU/plugin_woocommerce#8]
Gdy klient złoży zamówienie i przejdzie do bramki płatności payU, transakcja nie przejdzie, wracając do strony sklepu zamówienie zostaje wyczyszczone bez możliwości przywrócenia elementów w koszyku. Czy nie powinno być to opcją, albo sprawdzane czy płatność przeszła ?

**Comment by regdos** [comment]
Mechanizm składania zamówienia w WooCommerce działa tak, że najpierw jest zakładane zamówienie w WooCommerce a potem dopiero rozpoczyna się realizacja płatności.  Założenie zamówienia w WooCoomerce skutkuje wyczyszczeniem koszyka i po powrocie już to zamówienie istnieje w systemie WooCommerce.
