### ISSUE TITLE
Payment error: Oauth error: [code=401], [message=invalid_client - Can't find oauthClient with clientId = xxxx] (0)

### ISSUE THREAD

**Issue by MikeWizzard** [PayU/plugin_woocommerce#9]
Hi, i would like to thank you in advance, i have installed the plugin in my wordpress page and activated it, created a sandbox account in PayU website, added a POS with REST API (Checkout) and then configured the plugin in wordpress with the keys and ids generated in sandbox account.

anyway i always get this error:
Payment error: Oauth error: [code=401], [message=invalid_client - Can't find oauthClient with clientId = xxxx] (0)

can you please help me with it?

Best regards

**Comment by lgrzesiak** [comment]
Hi! 
The plugin is currently hardcoded with our production environment. Therefore, when you use sandbox credentials, you get this error. 
You may either use a production PayU account and the test payment method (you can create it here: https://secure.payu.com/boarding/#/form?lang=en) or find the following line in your WooCommerce installation: https://github.com/PayU/plugin_woocommerce/blob/master/includes/class-woocommerce-payu.php#L54 and change it to `OpenPayU_Configuration::setEnvironment('sandbox');`
